from .. import env

# ENVIRONMENT VARIABLES
VERSION = env.VERSION
ICONS_PATH = env.ICONS_PATH
SEPARATOR = env.SEPARATOR
MAYA_VERSION = env.MAYA_VERSION
DGA_NODES_SUPPORTED = env.DGA_NODES_SUPPORTED
# end globals


# ATTR
MAIN_BLENDSHAPE_STRING_IDENTIFIER = "mainBlendShape"
SPLIT_BLENDSHAPE_STRING_IDENTIFIER = "splitBlendShape"
WORK_BLENDSHAPE_STRING_IDENTIFIER = "workBlendShape"
HEAT_MAP_BLENDSHAPE_STRING_IDENTIFIER = "heatMapBlendShape"
SPLIT_ATTR_GRP_STRING_IDENTIFIER = "splitAttrGrp"
SPLIT_GRP_ATTR_STRING_IDENTIFIER = "splitGroups"
FACE_CTRL_STRING_IDENTIFIER = "faceCtrl"
NODE_NETWORK_CONTAINER_STRING_IDENTIFIER = "nodeNetwork"
BASE_MESH_STRING_IDENTIFIER = "baseMesh"
HEAT_MAP_MESH_STRING_IDENTIFIER = "heatMapMesh"
DGA_VISUALIZER_STRING_IDENTIFIER = "dgaVisualizer"
DGA_DELTA_STRING_IDENTIFIER = "dgaDelta"
DELTA_MAP_STRING_IDENTIFIER = "deltaMap"
# TARGET GROUP NAMES
PRIMARY_SHAPES_GRP_NAME = "Primaries_GRP"
COMBO_SHAPES_GRP_NAME = "Combos_GRP"
INBETWEEN_SHAPES_GRP_NAME = "Inbetweens_GRP"